[package]
name = "tensornetics-decentralized-ledger"
version = "0.1.0"
authors = ["Tensornetics <info@tensornetics.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
sha2 = "0.7"

[dev-dependencies]
rand = "0.7"
